# Config File

## Logging Parameters
logging:
  level:
    debug: true
    verbose: true
    info: true
    quiet: false
  output:
    file: "logs"
    fd: -1
  type: "Print"
  packet_hexdump: false

## Packet Parameters
packet:
  input:
    interface:
    pcapFile: other/pcaps/server_side_http_luke.pcap
  filter:
    BPF:
  snaplen: # Snapshot Length
  flush: 5

protocol: # Protocol Specific Options
  tcp:
    allowmissinginit: true # Support streams without SYN/SYN+ACK/ACK sequence
  http:
    port: 9999

profile: # Performance Testing
  cpu:
    enabled: false
  memory:
    enabled: false


