# Config File

## Logging Parameters
logging:
  level:
    debug: true
    verbose: true
    info: true
    quiet: false
  output:
    file: "logs"
    fd: -1
  type: "Print"
  packet_hexdump: false

## Packet Parameters
packet:
  input:
    interface: # en0
    pcapFile: tests/test1/tripwire-1597963966.pcap
  filter:
    BPF: "tcp"
  snaplen: # Snapshot Length
  flush: 50

protocol: # Protocol Specific Options
  tcp:
    allowmissinginit: true # Support streams without SYN/SYN+ACK/ACK sequence

# Measurements
measurements:
  - censor: China
    protocol: HTTP
    port: 9999
    options:
      direction: false # Should packet direction be taken into account - Default false
  - censor: China
    protocol: HTTP
    port: 80
    options:
      direction: true
  - censor: China
    protocol: HTTP
    port: 7777
    options:
      direction: true
  - censor: China
    protocol: SMTP
    port: 25
    options:
      direction: true
  - censor: China
    protocol: HTTPS
    port: 443
    options:
      direction: true
  - censor: China
    protocol: DNS
    port: 53
    options:
      direction: true

# Data Collectors
collectors:
  net: # Network Layer
    - type: IP
    - type: IPID
    - type: TTL
  tcp: # Transport Layer
    - type: Ports
    - type: Flags
    - type: SeqNum
    - type: Payload
      options:
        maxLength: 500
        direction: server # server: client->sever | client: server->client
    - type: Payload
      options:
        maxLength: 500
        direction: client # server: client->sever | client: server->client

profile: # Performance Testing
  cpu:
    enabled: false
    file: "cpu"
    fd: # file descriptor
  memory:
    enabled: false
    file: "mem"
    fd:
  httpServer:
    enabled: false

metrics:
  netw: "tcp"
  addr: ":9090"
