# Config File for detect.py

## Logging Parameters
logging:
  level:
    debug: true
    verbose: true
    info: true
    quiet: false
  output:
    file: "logs"
    fd: -1
  type: "Print"
  packet_hexdump: false

## Packet Parameters
packet:
  input:
    interface:
    pcapFile:
  filter:
    BPF:
  snaplen: # Snapshot Length
  flush: 5

protocol: # Protocol Specific Options
  tcp:
    allowmissinginit: true # Support streams without SYN/SYN+ACK/ACK sequence

measurements:
  - censor: China
    protocol: HTTP
    port: 80
    options:
      direcrtion: false # Should packet direction be taken into account

profile: # Performance Testing
  cpu:
    enabled: false
    file: "cpu"
    fd:
  memory:
    enabled: false
    file: "mem"
    fd:
  httpServer:
    enabled: false


