# Config File

## Logger Parameters
logger:
  debug: true
  outform: txt # txt or json

## Metrics Parameters
metrics:
  netw: "tcp"
  addr: ":9090"

## Parser Parameters
parser:
  input:
    interface:  #en0
    pcap: testdata/tripwire-1597963966.pcap
  snaplen: # Snapshot Length
  flush: 50
  tcp:
    allowmissinginit: true # Support streams without SYN/SYN+ACK/ACK sequence

# Detectors
detectors:
  - heuristic: RSTACKs
    protocol: HTTP
    port: 80
  - heuristic: RSTACKs
    protocol: SMTP
    port: 25
  - heuristic: RSTACKs
    protocol: HTTPS
    port: 443
  - heuristic: RSTACKs
    protocol: ECH
    port: 443
  - heuristic: RSTACKs
    protocol: HTTPS
    port: 443
  - heuristic: RSTACKs
    protocol: DNS
    port: 53
  - heuristic: WIN
    protocol: HTTP
    port: 80
  - heuristic: WIN
    protocol: HTTPS
    port: 443

# Data Collector
collector:
  fields:
    - IP
    - Ports
    - Direction
    - Timestamp
    - IPID
    - TTL
    - Flags
    - SeqNum
    - Payload
    - SNI
    - Extensions
  truncate_ips: true
  cli_maxlen: 0
  srv_maxlen: 0
